project_id = "vlspljhqyanpadbucmvq"

[functions.ttoke]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.call-candidate]
verify_jwt = false

[functions.bridge-candidate]
verify_jwt = false

[functions.zapier-webhook]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.hangup-call]
verify_jwt = false

[functions.receive-sms]
verify_jwt = false

[functions.incoming-call]
verify_jwt = false
